name: Test tap-mongodb
on:
  push:
    branches:
      - main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongo-version:
          - 3.6
          - 4.4
        python-version:
          - 3.11
        test-directory:
          - incremental_empty_collection
    services:
      mongo:
        image: mongo:${{ matrix.mongo-version}}
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        options: >-
          --health-cmd "mongo localhost:27017/test --quiet --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Test with pytest
        run: poetry run pytest
